language: java
jdk: oraclejdk8
install: true
script: if [ "$PERFORM_RELEASE" = "release" ]; then ./release.sh $RELEASE_VERSION $DEVELOPMENT_VERSION; else ./mvnw clean install; fi
cache:
  directories:
  - $HOME/.m2
after_success:
  - bash <(curl -s https://codecov.io/bash)